.github/workflows/basic.yml, lib/src/core/mod.rs, lib/src/core/verifier/policy/opa/mod.rs, lib/src/core/verifier/sample/mod.rs, lib/src/core/verifier/sgx/mod.rs, lib/src/core/verifier/tdx/mod.rs, lib/src/lib.rs
1.Enable the basic compile check for AS.
2.Fixed some warning errors that were detected by the `cargo fmt --all -- --check` and `cargo clippy -- -D warnings`.
Fixes: #5
Signed-off-by: zhouliang121 <liang.a.zhou@linux.alibaba.com>
=> AS: Add basic compile testing

.github/workflows/basic.yml
Disable the check for clippy::derive_partial_eq_without_eq, which is triggered
by generated code
The maintainer of tonic recommends this:
https://github.com/tokio-rs/prost/issues/661#issuecomment-1150140898
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
=> ci: Disable clippy lint check

rvps/src/lib.rs, rvps/src/store/mod.rs
Rename the component `Cache` to `Store` in RVPS to avoid ambiguity
=> fix: rename cache to store in RVPS

.gitignore, rvps/Cargo.toml, rvps/src/store/local_fs/README.md, rvps/src/store/local_fs/mod.rs, rvps/src/store/mod.rs
Due to https://github.com/confidential-containers/attestation-service/issues/11, an implementation of local file storage as `Store` is added in this pr. 
- Added local-fs storage using `sled` as engine.
- Added related document and interface tests of local-fs storage.
- All the data will be stored in the directory `/opt/attestation-server/reference_values`, where `/opt/attestation-server` is const `ATTESTATION_SERVER_WORKDIR ` in attestation-server.
=> [RVPS] Implement a local file storage as Cache

src/types.rs
The KBS may need to inspect the attestation results.
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>
=> types: Add AttestationResults getters

src/rvps/store/mod.rs, src/types.rs
Box::new(_) of default value can be simplified into Box::<_>::default(). See https://rust-lang.github.io/rust-clippy/master/index.html#box_default
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>
=> AS: Fix a couple of clippy warnings

src/rvps/extractors/extractor_modules/in_toto/shim/README.md
Added detailed parameter descriptions of the rust interface
=> docs: update document of rust-c wrapper of golang-in-toto

Cargo.toml, bin/grpc-as/proto/attestation.proto, bin/grpc-as/src/server.rs, src/lib.rs, src/types.rs, src/verifier/mod.rs, src/verifier/sample/mod.rs
This PR syncs with the[`kbs-types`](https://github.com/virtee/kbs-types) in order to have common KBS type definitions (`Tee`, `Attestation`) for both the AS and the KBS implementations.
One consequence of using the `kbs-types` crate is that we can no longer easily instantiate the `Sample` verifier. This PR puts it under a feature flag (`sample_verifier`). When turned on, the only available verifier is the `Sample` one. When turned off, `Sample` is not available.
=> kbs-types sync

Cargo.toml, src/verifier/mod.rs
Upstream `kbs-types` has updated a new test type `Sample`, thus the branch arm need to add the new type to pass the syntax check.
Related to https://github.com/confidential-containers/attestation-service/pull/47
=> fix: Sample verifier branch arm

Makefile, bin/grpc-as/src/server.rs
It was:
> for bin_name in grpc-as grpc-as-ctl; do \
install -D -m0755 target/release/$bin_name /usr/local/bin; \
done
install: cannot stat 'target/release/grpc-as': No such file or directory
install: cannot stat 'target/release/grpc-as-ctl': No such file or directory
Makefile:23: recipe for target 'install' failed
Now it should be okay,
>    Compiling attestation-service v0.1.0 (/home/dave/tmp/attestation-service)
Finished release [optimized] target(s) in 1m 58s
for bin_name in grpc-as; do \
install -D -m0755 target/release/$bin_name /usr/local/bin; \
done
=> Fix `make` && `make install` in the top dir

Cargo.toml, as-types/Cargo.toml, src/verifier/sample/mod.rs, src/verifier/tdx/mod.rs
The pubkey logic needs to be adjusted to match the upstream virtee/kbs-types structs. The fix needs to be coupled with the respective PRs on [Attestation Agent](https://github.com/confidential-containers/attestation-agent/pull/170) and [KBS](https://github.com/confidential-containers/attestation-agent/pull/170).
fixes #77
=> Update kbs-types to v0.2.0

src/verifier/tdx/mod.rs
This change was applied because the given tdvf does not support CCEL. Now newest tdvf is brought and
CCEL is supported, thus we do not need this workground.
=> TDX verifier: revert ccel change

src/policy_engine/opa/mod.rs
Pointer type conversion fails on s390x [here](https://github.com/confidential-containers/attestation-service/blob/0f7a70e98fc14890f2842dc66222b55ff28e1d99/src/policy_engine/opa/mod.rs#L59). This is a [known issue](https://github.com/rust-lang/rust/issues/60226) in rust and not specific to s390x. The best practice to fix this issue is to use `c_char` instead of `i8/u8` like [this](https://github.com/phanikishoreg/llvm-rs/commit/013d1e95406264df57879cda698dbe7a806b62b7).
=> Fix for pointer type error

Cargo.toml, src/verifier/tdx/eventlog.rs, src/verifier/tdx/mod.rs
This change updates the parsing method of TDX CCEL, The TD SHIM specific cc-measurement library is no longer used, Use the eventlog-rs library instead to support CCEL generated by both TDVF and TD SHIM.
cc @Xynnn007
=> TDX | Update CCEL parse logic to support both TDVF and TD-Shim

.github/dependabot.yml
For automatic tracking of dependencies and version updates.
=> github: Enable dependabot

attestation-service/Cargo.toml, attestation-service/src/policy_engine/opa/mod.rs, attestation-service/src/verifier/az_snp_vtpm/mod.rs
Readded the az-snp-vtpm verifier to the default verifiers, so it will get built in kbs, also adjusted the paths that have been used in the tests to match the refactoring.
fixes #102
=> Readd az-snp-vtpm verifier

CODEOWNERS
Have a more formalized way of defining maintainership.
attestation-service is maintained by the @attestation-service-maintainers team.
=> attestation-service: Add a CODEOWNERS file

attestation-service/src/lib.rs, attestation-service/src/utils.rs
Now for every key inside the parsed claims we will do a query from RVPS to get the list of the reference values. #105 brings nested parsed claims for TDX, which will make the mechanism broken.
This commit helps to flatten a nested parsed-claims, which will keep the original mechanism work.
cc @jialez0 
related to https://github.com/confidential-containers/attestation-service/pull/105
=> AS: flatten the parsed claims

Dockerfile.as
TPM libraries installed during first build in Dockerfile are not available at runtime.
`apt-get install libtss2-dev` will install libraries in `/usr/lib/x86_64-linux-gnu` that the Rust executable needs to load. However, this step happens only during the stage in the build to create the Rust executable. We need to copy these dependencies to the final half of the build so the executable can find them.
Confirmed that the gRPC server now starts with a locally built image
```
[2023-06-22T18:51:20Z INFO  grpc_as::server] Listen socket: 0.0.0.0:50004
[2023-06-22T18:51:20Z INFO  grpc_as::server] Start a local RVPS (Server mode)
```
Fixes https://github.com/confidential-containers/attestation-service/issues/113
=> Dockerfile: Copy TPM runtime dependencies

Cargo.lock, as-types/Cargo.toml, attestation-service/Cargo.toml
Preparing to upgrade KBS to `kbs-types 0.4`.
There is also a relaxation of `base64 0.21.2` to `base64 0.21` required, as KBS uses `jsonwebtoken`, which requires `base64 ^0.21.0`.
=> deps: update kbs-types to 0.4

Dockerfile.as, Dockerfile.rvps
rust:1.67 cannot build half v2.3.1 in CCA's PR
https://github.com/confidential-containers/attestation-service/actions/runs/5830448221/job/15811842602?pr=90
latest will choose the latest version of rust image to be the builder
helps https://github.com/confidential-containers/attestation-service/pull/90
cc @chendave @jialez0
=> dockerfile: update the builder image to rust:latest

attestation-service/Cargo.toml
Update csv-rs to support both 1.1.1 and 3.0.x versions of openssl.
=> as: Update csv-rs dep to rev bcf3bcc.

Cargo.lock, attestation-service/Cargo.toml
https://github.com/kinvolk/azure-cvm-tooling/commit/09a8a0d4a0c6347234de392064215037b09a1d0c
=> Update `az-snp-vtpm` version to avoid vendor openssl

attestation-service/Cargo.toml
The new version of csv-rs will support openssl 3.1.x.
Maybe there is same issue such as AA: https://github.com/confidential-containers/guest-components/issues/346
=> as: Update csv-rs dep to rev 05fbacd.

Cargo.lock, attestation-service/Cargo.toml, attestation-service/src/verifier/az_snp_vtpm/mod.rs
Azure rolled out a change in the HCL data structures, that'll break the current parsing logic of an az-snp-vtpm evidence.  Hence the bump to an update az-snp-vtpm crate, which accomodates this change.
=> Update az-snp-vtpm dependency

Dockerfile.as
Now we use ubuntu 20.04 as base image, the openssl version is 1.1.1 where the location of `libssl.so` is different from version 3.0+ and `csv-rs` crate now can only find `libssl.so` with version 3.0+
=> Update Docker base image version and install openssl

Cargo.lock, attestation-service/Cargo.toml, attestation-service/src/rvps/reference_value.rs, attestation-service/src/verifier/cca/mod.rs
According to the RMM spec, A7.2.3 Attestation token format [1], the CCA token has a client challenge sealed in the token, the challenge is generated when the CCA token is got from AA (attestation agent).
When the CCA token is validated by the veraison, a session nonce is created as well, semantically, the session nonce should be equal with the client challenge, this logic has been validated inside veraison service [2].
While the freshness also implies the session nonce key should equal with the nonce enveloped in the ear which is the format of attestation result [3], by this, we have:
```
client challenge in token == session nonce == ear's nonce
```
and thus avoid the replay attack.
NOTE: If the "client challenge in token != session nonce", vts service from Veraison takes it as a warning, …
=> Validate the freshness of session nonce
